/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux derp 3.13.0-55-generic x86_64"
#define LGL_COMPILED "Sun Sep 20 18:35:44 EEST 2015"
#define LGL_RELEASED "Tue Apr 29 19:18:48 CEST 2014"
#define LGL_VERSION "ayv"
#define LGL_ID "86bf266b9332599f1b876e28a02fe8427aeaa2db"
