/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux hp8x-77 4.8.0-51-generic x86_64"
#define LGL_COMPILED "Mon May 15 11:44:49 EEST 2017"
#define LGL_RELEASED "Tue Apr 29 19:18:48 CEST 2014"
#define LGL_VERSION "ayv"
#define LGL_ID "86bf266b9332599f1b876e28a02fe8427aeaa2db"
